import './globals.css';
import '@/node_modules/react-modal-video/scss/modal-video.scss';
import '@solana/wallet-adapter-react-ui/styles.css';

import Navbar from './components/Navbar/index';
import Footer from './components/Footer/index';
import { Providers } from './providers';

export const metadata = {
  title: 'CrCrypto',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
